In [398]:
# importing the necessary libraries

In [399]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [400]:
# reading data from the file

In [401]:
df = pd.read_csv('iris.csv',delimiter = ',')

In [402]:
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [403]:
# addin column names 

In [404]:
df.columns = ['sepal_length','sepal_width','petal_length','petal_width','Species']

In [405]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [406]:
new_row = {'sepal_length':5.1,'sepal_width':3.5,'petal_length':1.4,'petal_width':0.2,'Species':'Iris-setosa'}

In [407]:
df = df.append(new_row,ignore_index = True)

In [408]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [409]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width         Species
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica
149           5.1          3.5           1.4          0.2     Iris-setosa

In [410]:
# shuffling the data

In [411]:
#df = df.sample(frac=1)

In [412]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [413]:
# identifying the number of categories available

In [414]:
y = df['Species'].values

In [415]:
df['Species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64

In [416]:
# since there are 3 categories we are going to using k = 3.

In [417]:
y.shape

(150,)

In [418]:
X = df.drop(['Species'],axis = 1).values

In [419]:
X[:10]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2]])

In [420]:
# distance calculator

In [421]:
# distance between 2 points
def distance(p1,p2):
    
    return np.linalg.norm(p1 - p2)

In [422]:
# calculating centroid 

In [423]:
# centroid of a cluster
def centroid(cluster):
    
    length = cluster.shape[0]
    
    c0 = np.sum(cluster[:,0])
    c1 = np.sum(cluster[:,1])
    c2 = np.sum(cluster[:,2])
    c3 = np.sum(cluster[:,3])
    
    c0, c1, c2, c3 = c0/length , c1/length , c2/length , c3/length 
       
    return np.array([c0,c1,c2,c3])

In [424]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [425]:
# kmeans 

In [426]:
c1 = X[113].copy()
c2 = X[39].copy()
c3 = X[61].copy()
c1 = c1.reshape(1,4)
c2 = c2.reshape(1,4)
c3 = c3.reshape(1,4)

In [427]:
# cluster 1

In [428]:
c1

array([[5.8, 2.8, 5.1, 2.4]])

In [429]:
# cluster 2

In [430]:
c2

array([[5. , 3.5, 1.3, 0.3]])

In [431]:
# cluster 3

In [432]:
c3

array([[6. , 2.2, 4. , 1. ]])

In [433]:
# centroids for each cluster

In [434]:
centroid_1 = centroid(c1)
centroid_2 = centroid(c2)
centroid_3 = centroid(c3)

In [435]:
centroid_1

array([5.8, 2.8, 5.1, 2.4])

In [436]:
centroid_2

array([5. , 3.5, 1.3, 0.3])

In [437]:
centroid_3


array([6. , 2.2, 4. , 1. ])

In [438]:
# making a numpy array for all the clusters

In [439]:
cluster_centroid = np.array([centroid_1,centroid_2,centroid_3])

In [440]:
cluster_centroid

array([[5.8, 2.8, 5.1, 2.4],
       [5. , 3.5, 1.3, 0.3],
       [6. , 2.2, 4. , 1. ]])

In [441]:
cluster_centroid = np.round(cluster_centroid,2)

In [442]:
cluster_centroid

array([[5.8, 2.8, 5.1, 2.4],
       [5. , 3.5, 1.3, 0.3],
       [6. , 2.2, 4. , 1. ]])

In [443]:
c1

array([[5.8, 2.8, 5.1, 2.4]])

In [444]:
# implementation of k-means

In [445]:
counter = 0

while(1):
    
    counter +=1
    #print(counter)
    
    if counter>1:
        cluster_centroid = new_centroids.copy()
    
    for x in X[3:]:
        
        x = x.reshape(1,4)
        
        distance_1 = np.round(distance(x,centroid(c1)),2)
        distance_2 = np.round(distance(x,centroid(c2)),2)
        distance_3 = np.round(distance(x,centroid(c3)),2)
        
        #print(distance_1,distance_2,distance_3)
        
        for i in range(c1.shape[0]):
            if ((c1[i] == x).all()):
                c1 = np.delete(c1,i,0)
                break
            else:
                pass
        
        for i in range(c2.shape[0]):
            if ((c2[i] == x).all()):
                c2 = np.delete(c2,i,0)
                break
                
        for i in range(c3.shape[0]):
            if ((c3[i] == x).all()):
                c3 = np.delete(c3,i,0)
                break
        
        flag = 0
        
        if flag == 0:
            if distance_1 <= distance_2 and distance_1 <= distance_3:
                c1 = np.vstack((c1,x))
                flag = 1

        if flag == 0: 
            if distance_2 <= distance_3 and distance_2 <= distance_1:
                c2 = np.vstack((c2,x))
                flag = 1
        
        if flag == 0:
            if distance_3 <= distance_1 and distance_3 <= distance_2:
                c3 = np.vstack((c3,x))
                flag = 1
    
    
    new_centroids = np.array([centroid(c1),centroid(c2),centroid(c3)])
    new_centroids = np.round(new_centroids,2)
    
    
    if counter>1:
        if((new_centroids == cluster_centroid).all()):
            #print(True)
            break
    

In [446]:
# final clusters

In [447]:
c1.shape

(39, 4)

In [448]:
c2.shape

(45, 4)

In [449]:
c3.shape 

(60, 4)

In [450]:
# calculating cluster accuracy

In [451]:
miss_1 = 0
for i in range(X.shape[0]):
    if list(X[i]) in c1.tolist():
        if y[i] != 'Iris-virginica':
            miss_1+=1

In [452]:
miss_1

3

In [453]:
miss_2 = 0
for i in range(X.shape[0]):
    if list(X[i]) in c2.tolist():
        if y[i] != 'Iris-setosa':
            miss_2+=1

In [454]:
miss_2

0

In [455]:
miss_3 = 0
for i in range(X.shape[0]):
    if list(X[i]) in c3.tolist():
        if y[i] != 'Iris-versicolor':
            miss_3+=1

In [456]:
miss_3

14

In [457]:
accuracy = (1 - (miss_1 + miss_2 + miss_3 )/ 150) * 100

In [458]:
# accuracy of the model in %

In [459]:
accuracy

88.66666666666667